In [1]:
import pandas as pd

df=pd.read_csv("us.csv")
#pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
df

,Name,Email,Financial Status,Paid at,Fulfillment Status,Fulfilled at,Accepts Marketing,Currency,Subtotal,Shipping,Taxes,Total,Discount Code,Discount Amount,Shipping Method,Created at,Lineitem quantity,Lineitem name,Lineitem price,Lineitem compare at price,Lineitem sku,Lineitem requires shipping,Lineitem taxable,Lineitem fulfillment status,Billing Name,Billing Street,Billing Address1,Billing Address2,Billing Company,Billing City,Billing Zip,Billing Province,Billing Country,Billing Phone,Shipping Name,Shipping Street,Shipping Address1,Shipping Address2,Shipping Company,Shipping City,Shipping Zip,Shipping Province,Shipping Country,Shipping Phone,Notes,Note Attributes,Cancelled at,Payment Method,Payment Reference,Refunded Amount,Vendor,Outstanding Balance,Employee,Location,Device ID,Id,Tags,Risk Level,Source,Lineitem discount,Tax 1 Name,Tax 1 Value,Tax 2 Name,Tax 2 Value,Tax 3 Name,Tax 3 Value,Tax 4 Name,Tax 4 Value,Tax 5 Name,Tax 5 Value,Phone,Receipt Number,Duties,Billing Province Name,Shipping Province Name,Payment ID,Payment Terms Name,Next Payment Due At,Payment References,Jaar,Maand,Dag
0,US4419,robelm11@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-12-31 12:13:05,1,Patta Embroidered Fire Panther Hooded Sweater ...,152.0,NaN,POC-AW25-2050-325-0026-001-L,True,True,fulfilled,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025,12,31
1,US4418,weirdhumanstuff@gmail.com,refunded,2025-12-31 04:53:41 -0500,unfulfilled,NaN,no,USD,84.0,16.8,0.0,100.8,NaN,0.0,UPS Express Saver,2025-12-31 05:52:35,1,Patta Script Logo Sports Socks (Melange Grey) ...,20.0,NaN,POC-AW25-2020-396-0016-050-42-46,True,True,pending,Briana Wright,213 Miranda Way,213 Miranda Way,NaN,NaN,Georgetown,'78633,TX,US,2544625090,Briana Wright,"1274 N Crescent Heights Blvd, Apt 303",1274 N Crescent Heights Blvd,Apt 303,NaN,West Hollywood,'90046,CA,US,2544625090,NaN,delivery_defense_score: 767,2026-01-07 13:00:43 -0500,Adyen Payments - Credit Cards,rekqdmRyben2RgCNxZG40jPNq,100.8,Patta,0.0,NaN,NaN,NaN,1.652610e+13,DeliveryDefense risk level: Low,Low,web,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Texas,California,rekqdmRyben2RgCNxZG40jPNq,NaN,NaN,rekqdmRyben2RgCNxZG40jPNq + aZePGfyJl0rzRvozbM...,2025,12,31
2,US4418,weirdhumanstuff@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-12-31 05:52:35,1,Patta Many Moods T-Shirt (Black) - M,64.0,NaN,POC-AW25-1000-290-0075-001-M,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025,12,31
3,US4417,matthew.oelz@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-12-30 18:02:46,1,Patta Dice Set (Black),44.0,NaN,PA-AW23-DICE-SET-001,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025,12,30
4,US4416,brittanyanngreen@icloud.com,refunded,2025-12-28 01:12:21 -0500,unfulfilled,NaN,yes,USD,53.0,16.8,0.0,69.8,NaN,0.0,UPS Express Saver,2025-12-28 02:11:19,1,Patta Cartoon Cap (Birch),53.0,NaN,POC-AW25-4100-815-0011-159,True,True,pending,Brittany Green,15 Greenridge Ln,15 Greenridge Ln,NaN,NaN,Bentonville,'72712,AR,US,NaN,Brittany Green,15 Greenridge Ln,15 Greenridge Ln,NaN,NaN,Bentonville,'72712,AR,US,4796315026,NaN,delivery_defense_score: 873,2026-01-07 09:57:25 -0500,Adyen Payments - Credit Cards,rnXppyDxnL07d2LF6Rog9bJVu,69.8,Patta,0.0,NaN,NaN,NaN,1.652105e+13,"DeliveryDefense risk level: Low, SupplierChina...",Low,web,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Arkansas,Arkansas,rnXppyDxnL07d2LF6Rog9bJVu,NaN,NaN,rnXppyDxnL07d2LF6Rog9bJVu + a2UQFI07yGaKmNVOEK...,2025,12,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4914,US1003,leander@patta.nl,paid,2023-08-21 06:12:24 -0400,fulfilled,2023-09-01 10:43:54 -0400,no,USD,194.0,23.5,0.0,217.5,NaN,0.0,UPS Express,2023-08-21 10:12:23,1,Patta Apple T-Shirt (Odyssey Gray) - M,45.0,NaN,POC-SS23-APPLE-TS-002-M,True,True,fulfilled,Christopher Guzman TEST,504 E 79th St apt 2c,504 E 79th St apt 2c,NaN,NaN,New York,'10075,NY,US,NaN,Christopher Guzman TEST,504 E 79th St apt 2c,504 E 79th St apt 2c,NaN,NaN,New York,'10075,NY,US,NaN,NaN,NaN,NaN,manual,rC5TYcZQZGrmqlF0ywIiUOrsY,0.0,Patta,0.0,NaN,NaN,NaN,5.442753e+12,NaN,Low,shopify_draft_order,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New York,New York,rC5TYcZQZGrmqlF0ywIiUOrsY,NaN,NaN,rC5TYcZQZGrmqlF0ywIiUOrsY,2023,8,21
4915,US1003,leander@patta.nl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-08-21 10:12:23,1,Patta Argyle Knitted Cardigan (Light Brown Mel...,149.0,NaN,POC-SS23-ARGYLE-KC-001-L,True,True,fulfilled,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,8,21
4916,#1002,leander@patta.nl,refunded,2023-07-27 08:43:08 -0400,unfulfilled,NaN,no,USD,194.0,0.0,0.0,194.0,NaN,0.0,NaN,2023-07-27 12:43:07,1,Patta Apple T-Shirt (Black) - XL,45.0,NaN,POC-SS23-APPLE-TS-001-XL,True,True,pending,Christopher Guzman TEST,504 E 79th St apt 2c,504 E 79th St apt 2c,NaN,NaN,New York,'10075,NY,US,NaN,Christopher Guzman TEST,504 E 79th St apt 2c,504 E 79th St apt 2c,NaN,NaN,New York,'10075,NY,US,NaN,NaN,NaN,2023-08-21 05:53:03 -0400,manual,rnA6iefyUdyntvkZIGqgln4eR,194.0,Patta,0.0,NaN,NaN,NaN,5.413739e+12,NaN,Low,shopify_draft_order,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New York,New York,rnA6iefyUdyntvkZIGqgln4eR,NaN,NaN,rnA6iefyUdyntvkZIGqgln4eR + #1002.2,2023,7,27
4917,#1002,leander@patta.nl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-07-27 12:43:07,1,Patta Argyle Knitted Cardigan (Light Brown Mel...,149.0,NaN,POC-SS23-ARGYLE-KC-001-M,True,True,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,7,27
4918,#1001,jeffrey@patta.nl,refunded,2023-07-05 08:48:16 -0400,unfulfilled,NaN,no,USD,45.0,0.0,0.0,45.0,NaN,0.0,NaN,2023-07-05 12:48:16,1,Patta Apple T-Shirt (Black) - XL,45.0,NaN,POC-SS23-APPLE-TS-001-XL,True,True,pending,Jeffrey Verwey,Bilderdijkstraat 77,Bilderdijkstraat 77,NaN,NaN,Amsterdam,1053 KM,AL,US,+31631766395,Jeffrey Verwey,Bilderdijkstraat 77,Bilderdijkstraat 77,NaN,NaN,Amsterdam,1053 KM,AL,US,+31631766395,NaN,NaN,2023-08-21 05:52:57 -0400,manual,ranUwCI8JN2aWjhTslgnTNnuq,45.0,Patta,0.0,NaN,NaN,NaN,5.364410e+12,NaN,Low,shopify_draft_order,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alabama,Alabama,ranUwCI8JN2aWjhTslgnTNnuq,NaN,NaN,ranUwCI8JN2aWjhTslgnTNnuq + #1001.2,2023,7,5

In [7]:
df["Created at"] = pd.to_datetime(df["Created at"], errors="coerce", utc=True)

# Alleen timezone verwijderen als het echt timezone-aware is
if df["Created at"].dt.tz is not None:
    df["Created at"] = df["Created at"].dt.tz_localize(None)

df["Jaar"] = df["Created at"].dt.year
df["Maand"] = df["Created at"].dt.month
df["Dag"] = df["Created at"].dt.day

df

,Name,Email,Financial Status,Paid at,Fulfillment Status,Fulfilled at,Accepts Marketing,Currency,Subtotal,Shipping,Taxes,Total,Discount Code,Discount Amount,Shipping Method,Created at,Lineitem quantity,Lineitem name,Lineitem price,Lineitem compare at price,Lineitem sku,Lineitem requires shipping,Lineitem taxable,Lineitem fulfillment status,Billing Name,Billing Street,Billing Address1,Billing Address2,Billing Company,Billing City,Billing Zip,Billing Province,Billing Country,Billing Phone,Shipping Name,Shipping Street,Shipping Address1,Shipping Address2,Shipping Company,Shipping City,Shipping Zip,Shipping Province,Shipping Country,Shipping Phone,Notes,Note Attributes,Cancelled at,Payment Method,Payment Reference,Refunded Amount,Vendor,Outstanding Balance,Employee,Location,Device ID,Id,Tags,Risk Level,Source,Lineitem discount,Tax 1 Name,Tax 1 Value,Tax 2 Name,Tax 2 Value,Tax 3 Name,Tax 3 Value,Tax 4 Name,Tax 4 Value,Tax 5 Name,Tax 5 Value,Phone,Receipt Number,Duties,Billing Province Name,Shipping Province Name,Payment ID,Payment Terms Name,Next Payment Due At,Payment References,Jaar,Maand,Dag
0,US4419,robelm11@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-12-31 12:13:05,1,Patta Embroidered Fire Panther Hooded Sweater ...,152.0,NaN,POC-AW25-2050-325-0026-001-L,True,True,fulfilled,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025,12,31
1,US4414,nzkatapo@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-12-26 03:00:25,1,Patta Quilted Script Logo Puffer Jacket (Navy)...,324.0,NaN,POC-AW25-3200-348-0031-202-L,True,True,fulfilled,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025,12,26
2,US4412,agretana69@icloud.com,paid,2025-12-25 00:21:41 -0500,fulfilled,2026-01-08 15:51:28 -0500,yes,USD,66.0,16.8,0.0,82.8,NaN,0.0,UPS Express Saver,2025-12-25 01:20:45,1,Patta Lighters T-Shirt (Parisian Night ) - XL,64.0,NaN,POC-AW25-1000-290-0095-202-XL,True,True,fulfilled,Andres Retana,9001 Shellwood Ct,9001 Shellwood Ct,NaN,NaN,Raleigh,'27617,NC,US,NaN,Andres Retana,9001 Shellwood Ct,9001 Shellwood Ct,NaN,NaN,Raleigh,'27617,NC,US,9199876709,NaN,delivery_defense_score: 891,NaN,Adyen Payments - Credit Cards,rfETfyiWUaXtr6wbW1or3e12i,0.0,Patta,0.0,NaN,NaN,NaN,1.651526e+13,"DeliveryDefense risk level: Low, SupplierChina...",Low,web,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,North Carolina,North Carolina,rfETfyiWUaXtr6wbW1or3e12i,NaN,NaN,rfETfyiWUaXtr6wbW1or3e12i + aSF3q6fhQlGwkgGOOy...,2025,12,25
3,US4411,corey.lepore@gmail.com,paid,2025-12-24 01:39:25 -0500,fulfilled,2026-01-04 05:45:25 -0500,yes,USD,75.0,21.0,0.0,96.0,NaN,0.0,UPS Express,2025-12-24 02:38:25,1,Patta Oversized Tote Bag (Black),75.0,NaN,POC-AW25-3500-380-0001-001,True,True,fulfilled,Corey Lepore,2 Lyons Rd,2 Lyons Rd,NaN,NaN,Armonk,'10504,NY,US,NaN,Corey Lepore,2 Lyons Road,2 Lyons Road,NaN,NaN,Armonk,'10504,NY,US,9144190346,NaN,delivery_defense_score: 880,NaN,Adyen Payments - Credit Cards,rBsHHagYQ9qkJ9Ta5tB4FIkqY,0.0,Patta,0.0,NaN,NaN,NaN,1.651408e+13,"DeliveryDefense risk level: Low, SupplierChina...",Low,web,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New York,New York,rBsHHagYQ9qkJ9Ta5tB4FIkqY,NaN,NaN,rBsHHagYQ9qkJ9Ta5tB4FIkqY + aCcnyMDun4rw99nuLy...,2025,12,24
4,US4410,hemicuda620@gmail.com,paid,2025-12-23 17:03:23 -0500,fulfilled,2026-01-05 14:45:31 -0500,yes,USD,152.0,16.8,0.0,168.8,NaN,0.0,UPS Express Saver,2025-12-23 18:01:59,1,Patta Embroidered Fire Panther Hooded Sweater ...,152.0,NaN,POC-AW25-2050-325-0026-001-L,True,True,fulfilled,Aspen Goodman,"576 Jaques Avenue, 2",576 Jaques Avenue,2,NaN,Rahway,'07065,NJ,US,7324231758,Aspen Goodman,"576 Jaques Avenue, 2",576 Jaques Avenue,2,NaN,Rahway,'07065,NJ,US,7324231758,NaN,delivery_defense_score: 866,NaN,Adyen Payments - Credit Cards,r7uOzcrG6pVrS9zGVejo25uNn,0.0,Patta,0.0,NaN,NaN,NaN,1.651354e+13,"DeliveryDefense risk level: Low, SupplierChina...",Low,web,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New Jersey,New Jersey,r7uOzcrG6pVrS9zGVejo25uNn,NaN,NaN,r7uOzcrG6pVrS9zGVejo25uNn + at7dqUCKyuJDiSZK9a...,2025,12,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3549,US1007,hana.salem@hotmail.fr,paid,2023-10-04 11:56:58 -0400,unfulfilled,NaN,no,USD,45.0,0.0,0.0,45.0,NaN,0.0,NaN,2023-10-04 15:56:58,1,Patta Apple T-Shirt (Odyssey Gray) - M,45.0,NaN,POC-SS23-APPLE-TS-002-M,True,True,pending,Don't ship ME,1600 Amphitheatre Pkwy,1600 Amphitheatre Pkwy,NaN,Pattta,Mountain View,'94043,CA,US,NaN,Don't ship ME,1600 Amphitheatre Pkwy,1600 Amphitheatre Pkwy,NaN,Pattta,Mountain View,'94043,CA,US,NaN,NaN,NaN,NaN,manual,r8NVWFtC5aAgKKDDUC45iyaCh,0.0,Patta,0.0,Hana Salem,NaN,NaN,5.514814e+12,NaN,Low,shopify_draft_order,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,California,California,r8NVWFtC5aAgKKDDUC45iyaCh,NaN,NaN,r8NVWFtC5aAgKKDDUC45iyaCh,2023,10,4
3550,US1006,leander@patta.nl,paid,2023-09-28 09:47:07 -0400,fulfilled,2023-09-28 09:49:17 -0400,no,USD,45.0,0.0,0.0,45.0,NaN,0.0,NaN,2023-09-28 13:47:07,1,Patta Apple T-Shirt (Black) - XS,45.0,NaN,POC-SS23-APPLE-TS-001-XS,True,True,fulfilled,Christopher Guzman TEST,504 E 79th St apt 2c,504 E 79th St apt 2c,NaN,NaN,New York,'10075,NY,US,NaN,Christopher Guzman TEST,"317 Dundas St W, Toronto, ON M5T 1G4, Canada","317 Dundas St W, Toronto, ON M5T 1G4, Canada",NaN,NaN,toronto,M5T 1G4,ON,CA,NaN,"2023-09-29 15:50 UTC\nReturnGO, RMA2156701:\nR...",NaN,NaN,manual,r0YurWeCgffOT8z8VPZn5rBRz,0.0,Patta,0.0,Hana Salem,NaN,NaN,5.508499e+12,Return requested via ReturnGO,Low,shopify_draft_order,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New York,Ontario,r0YurWeCgffOT8z8VPZn5rBRz,NaN,NaN,r0YurWeCgffOT8z8VPZn5rBRz,2023,9,28
3551,US1005,tomas@patta.nl,paid,2023-09-28 09:43:44 -0400,fulfilled,2023-09-28 09:49:33 -0400,no,USD,45.0,0.0,7.5,45.0,NaN,0.0,NaN,2023-09-28 13:43:44,1,Patta Apple T-Shirt (Black) - S,45.0,NaN,POC-SS23-APPLE-TS-001-S,True,True,fulfilled,TEST ACCOUNT DONT SHIP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TEST ACCOUNT DONT SHIP TEST ACCOUNT DONT SHIP,"1600 Pennsylvania Avenue NW, Washington, DC 20...","1600 Pennsylvania Avenue NW, Washington, DC 20...",NaN,Patta,DC,'20500,DC,US,NaN,"2023-09-29 15:02 UTC\nReturnGO, RMA2156433:\nR...",NaN,NaN,manual,rZrdQkDb5uw7p7ohMxUa79w6K,0.0,Patta,0.0,Hana Salem,Patta UK - Bleckmann Warehouse,NaN,5.508496e+12,Return requested via ReturnGO,Low,shopify_draft_order,0.0,GB VAT 20%,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Washington DC,rZrdQkDb5uw7p7ohMxUa79w6K,NaN,NaN,rZrdQkDb5uw7p7ohMxUa79w6K,2023,9,28
3552,US1003,leander@patta.nl,paid,2023-08-21 06:12:24 -0400,fulfilled,2023-09-01 10:43:54 -0400,no,USD,194.0,23.5,0.0,217.5,NaN,0.0,UPS Express,2023-08-21 10:12:23,1,Patta Apple T-Shirt (Odyssey Gray) - M,45.0,NaN,POC-SS23-APPLE-TS-002-M,True,True,fulfilled,Christopher Guzman TEST,504 E 79th St apt 2c,504 E 79th St apt 2c,NaN,NaN,New York,'10075,NY,US,NaN,Christopher Guzman TEST,504 E 79th St apt 2c,504 E 79th St apt 2c,NaN,NaN,New York,'10075,NY,US,NaN,NaN,NaN,NaN,manual,rC5TYcZQZGrmqlF0ywIiUOrsY,0.0,Patta,0.0,NaN,NaN,NaN,5.442753e+12,NaN,Low,shopify_draft_order,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New York,New York,rC5TYcZQZGrmqlF0ywIiUOrsY,NaN,NaN,rC5TYcZQZGrmqlF0ywIiUOrsY,2023,8,21
3553,US1003,leander@patta.nl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-08-21 10:12:23,1,Patta Argyle Knitted Cardigan (Light Brown Mel...,149.0,NaN,POC-SS23-ARGYLE-KC-001-L,True,True,fulfilled,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,8,21

In [11]:
# import numpy as np
# import seaborn as sns
# import matplotlib.pyplot as plt

# df["Subtotal"] = (
#     df["Subtotal"]
#     .astype(str)
#     .str.replace(",", "")
#     .astype(float)
# )

# plt.figure()
# sns.barplot(data=df, x="Maand", y="Subtotal")

# plt.title("Totale omzet per maand")
# plt.xlabel("Maand")
# plt.ylabel("Totale omzet  10x")

# plt.show()